###
POST http://localhost:8080/minter/tx-body
Content-Type: application/json

{
  "address": "addr_test1qzx9hu8j4ah3auytk0mwcupd69hpc52t0cw39a65ndrah86djs784u92a3m5w475w3w35tyd6v3qumkze80j8a6h5tuqq5xe8y",
  "quantity": 1
}

###
POST http://localhost:8080/minter/mint
Content-Type: application/json

{
  "reqId": "req_id_f4c7de9f-19e6-4422-bae1-b939e36e9312",
  "walletWitnessHex": "a10081825820720f3255e00946db45e823ca03d7300ccd0f488a0b5008f47740b6f5c5186aad58403bbc41d62247b7132ba32fcd6126e050144e85265aa37ff95723477f48db5261731b8cb7c630eb806f6c968d9e8b40ea0c0a8e55c84d828e5a6029252122950c"
}

###
POST http://localhost:8080/faucet/bloxb1
Content-Type: application/json


###
POST http://localhost:8080/faucet/bloxb1/addresses
Content-Type: application/json

{
  "noOfAccounts": 0,
  "noOfAddresses": 20
}

###
GET http://localhost:8080/faucet/bloxb1/addresses

###
POST http://localhost:8080/faucet/bloxb1/addresses/refresh
Content-Type: application/json

{
  "noOfAccounts": 0,
  "noOfAddresses": 120
}

###
## Distribute
## Policy : c48f707fea6f08af67a8c06c9bea5b3ec847f5901dc08420cd7f8ade  BLOXB

POST http://localhost:8080/faucet/bloxb1/topup
Content-Type: application/json

{
  "sender": "addr_test1qpe9rktvrx6dmh5xz9tkk9eqlyeevtqhe4wxa6m0cftlawxhv8kqvcufzswvffew2k24lqjzgke7yeu8vgdarctqxlls5hnffy",
  "policyId": "c48f707fea6f08af67a8c06c9bea5b3ec847f5901dc08420cd7f8ade",
  "assetName": "BLOXB",
  "qty": 150000000
}


###
## Distribute

POST http://localhost:8080/faucet/bloxb1/distribution
Content-Type: application/json

{
  "receiver": "addr_test1qpe9rktvrx6dmh5xz9tkk9eqlyeevtqhe4wxa6m0cftlawxhv8kqvcufzswvffew2k24lqjzgke7yeu8vgdarctqxlls5hnffy",
  "policyId": "c48f707fea6f08af67a8c06c9bea5b3ec847f5901dc08420cd7f8ade",
  "assetName": "BLOXB",
  "qty": 500
}

###
POST http://localhost:8080/auth/session
Content-Type: application/json

{
  "address": "addr_test1qpjvn3qur4y04rf9yutvvslzz9lz4747mv3wxrjm982tasn87eydaex66824nc44gs9asm8njqsfgny6gz00xa3477csfttq43",
  "message": "hello",
  "signature": "signature"
}

###
POST http://localhost:8080/auth/session/validate
Content-Type: application/json

{
  "sessionId": "session_id_ad9a08f0-c47f-48f4-a293-c50e6d897802",
  "address": "addr_test1qpjvn3qur4y04rf9yutvvslzz9lz4747mv3wxrjm982tasn87eydaex66824nc44gs9asm8njqsfgny6gz00xa3477csfttq43"
}
